# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/FalconSocial/pre-commit-python-sorter
    rev: b57843b0b874df1d16eb0bef00b868792cb245c2 # Current master (as of 2020-06-04)
    hooks:
      - id: python-import-sorter
        args: ["--silent-overwrite"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
        exclude: "^(webapp/__tests__/__snapshots__/)"
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: debug-statements

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--line-length=79]
